// <auto-generated />
namespace TechFu.Nirvana.EventStoreSample.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NameToCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameToCart));
        
        string IMigrationMetadata.Id
        {
            get { return "201608041150268_NameToCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
